2020-07-02 15:43:59,842 ERROR: Exception on /login [GET] [in c:\dash\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\dash\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\dash\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\dash\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\dash\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\dash\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\dash\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\dash\microblog\app\routes.py", line 72, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\dash\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\dash\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\dash\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\dash\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\dash\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\dash\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\dash\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\dash\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\dash\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\dash\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\dash\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\dash\microblog\app\templates\base.html", line 21, in block "navbar"
    <li><a href="{{ url_for('index') }}">Home</a></li>
jinja2.exceptions.UndefinedError: '_' is undefined
2020-07-02 15:44:45,932 INFO: Microblog startup [in C:\dash\microblog\app\__init__.py:42]
2020-07-02 15:47:28,162 INFO: Microblog startup [in C:\dash\microblog\app\__init__.py:42]
2020-07-02 15:48:27,698 INFO: Microblog startup [in C:\dash\microblog\app\__init__.py:42]
